# -*- coding: utf-8 -*-
"""FizzBuzz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PEL_iV0_vqWgAw-ZJ_Pc7Il8U9A5LJzL
"""

for n in range(1,101):
  if n% 3 == 0 and n % 5 == 0:
    print("fizzbuzz")
  elif n% 3 == 0:
    print("fizz")
  elif n% 5 == 0:
    print("buzz")
  else:
    print(n)